### ISSUE TITLE
Melhoria Entrega Contínua

### ISSUE THREAD

**Issue by henmerlin** [pjefika/FulltestNode#93]
Disponibilizar serviço REST para:
- [ ] Disponibilizar `endpoints` para o client;
Disponibilizar `websocket` para:
- [ ] Envio de informativos em broadcast; 
- [ ] Validação de versão atual e atualização.
